# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 285abe7c5e11593e675127f59182ca3ac7577e93eab7baddafdcf43ff8fcd62e82a38ad7c32960b49470b9d30b1df8c4b8edb4275a742d4b21e4691df576ca2f

test:
  secret_key_base: 0f23d92f6465dabd9d7009b5590b5c498bf5b19250989e7fbe85d1f3399cf44dd08fcede78c656f9095deddc7e8144d339d1a71798f661fc9a0e81b7232c21b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
